# Generated by Django 3.0.5 on 2020-04-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=150, verbose_name='circule name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Verified cicles are also know as official communities.', verbose_name='verifief circle')),
                ('is_public', models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone knows about their existence.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited cicles can grow up to fixed number of members.', verbose_name='limited group')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If cicles is limited, this will be the limit on the number of menbers.')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
